apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: lboscan-site-tls
spec:
  secretName: lboscan-site-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: lboscan.site
  dnsNames:
    - lboscan.site
    - www.lboscan.site
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - lboscan.site
          - www.lboscan.site
